export interface IAnalyz{

    id?: number | null,
    firstname: string | undefined,
    lastname: string | undefined,
    middlename: string | undefined,
    gender: number | null,
    hormonalBackground: number | null,
    cardivascularSystem: number | null,
    genitourinarySystem: number | null,
    gastrointestinalTract: number | null,
    angiopathy: number | null,
    tumorsOtherLocalization: number | null,
    RBC: number | null,
    MCV: number | null,
    RDW: number | null,
    RDWa: number | null,
    HCT: number | null,
    PLT: number | null,
    MPV: number | null,
    PDW: number | null,
    PCT: number | null,
    LPCR: number | null,
    WBC: number | null,
    HGB: number | null,
    MCH: number | null,
    MCHC: number | null,
    LYM: number | null,
    GRAN: number | null,
    MID: number | null,
    LIMProcent: number | null,
    GRAProcent: number | null,
    MIDProcent: number | null,
    NEUT: number | null,
    BO: number | null,
    BASO: number | null,
    MON: number | null,
    Ultrasound: number | null,
    metastasa: number | null,
    answer: number,
    createdAt?: Date,
    updatedAt?: Date,
    user?: {email: string} | string | null,

}