export interface ITable{

    id?: number,
    gender: number,
    hormonalBackground: number,
    cardivascularSystem: number,
    genitourinarySystem: number,
    gastrointestinalTract: number,
    angiopathy: number,
    tumorsOtherLocalization: number,
    RBC: number,
    MCV: number,
    RDW: number,
    RDWa: number,
    HCT: number,
    PLT: number,
    MPV: number,
    PDW: number,
    PCT: number,
    LPCR: number,
    WBC: number,
    HGB: number,
    MCH: number,
    MCHC: number,
    LYM: number,
    GRAN: number,
    MID: number,
    LIMProcent: number,
    GRAProcent: number,
    MIDProcent: number,
    NEUT: number,
    BO: number,
    BASO: number,
    MON: number,
    Ultrasound: number,
    createdAt?: Date,
    updatedAt?: Date

}